

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # DynamoDB Table for Corn Pests
  CornPestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "PestID"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "PestID"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "CornPests"

  # DynamoDB Table for Wheat Pests
  WheatPestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "PestID"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "PestID"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "WheatPests"

  # Lambda Execution Role for accessing DynamoDB and logging
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"

  # Lambda function to initialize corn pests data
  InitCornPestsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          const AWS = require("aws-sdk");
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event, null, 2));
            var params = {
              RequestItems: {
                "CornPests": [
                  {
                    PutRequest: {
                      Item: {
                        PestID: "CORN001",
                        PestName: "Corn Earworm"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        PestID: "CORN002",
                        PestName: "Fall Armyworm"
                      }
                    }
                  }
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                console.error("Unable to add pests:", JSON.stringify(err, null, 2));
              } else {
                console.log("Corn pests added successfully.");
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      Runtime: nodejs18.x
      Timeout: 60

  # Lambda function to initialize wheat pests data
  InitWheatPestsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          const AWS = require("aws-sdk");
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event, null, 2));
            var params = {
              RequestItems: {
                "WheatPests": [
                  {
                    PutRequest: {
                      Item: {
                        PestID: "WHEAT001",
                        PestName: "Hessian Fly"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        PestID: "WHEAT002",
                        PestName: "Russian Wheat Aphid"
                      }
                    }
                  }
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                console.error("Unable to add pests:", JSON.stringify(err, null, 2));
              } else {
                console.log("Wheat pests added successfully.");
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      Runtime: nodejs18.x
      Timeout: 60

  # Initialize CornPests Table
  InitializeCornPestsTable:
    Type: Custom::InitCornPestsFunction
    DependsOn: CornPestsTable
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitCornPestsFunction , "Arn" ]
      DynamoTableName:
        Ref: CornPestsTable

  # Initialize WheatPests Table
  InitializeWheatPestsTable:
    Type: Custom::InitWheatPestsFunction
    DependsOn: WheatPestsTable
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitWheatPestsFunction , "Arn" ]
      DynamoTableName:
        Ref: WheatPestsTable

Outputs:
  CornPestsApi:
    Description: "Corn pests table initialized"
    Value: !Ref CornPestsTable

  WheatPestsApi:
    Description: "Wheat pests table initialized"
    Value: !Ref WheatPestsTable
